###############################################################################
# purpose: Assignment 1 Ed Solution
# created: 8-25-2015
#  author: J. Edward Swan II
###############################################################################
.PRECIOUS = example.cpp parseTree.h 

example.exe: example.cpp parseTree.h
	g++ -o $@ example.cpp

clean: 
	$(RM) *.o *~ example.exe

